### PR TITLE
add lookup GM subcommand

### PR DESCRIPTION
**Pull request by 55Honey**
new command:
`.raf lookup $accountId`

### CODE REVIEW

**Comment by ghost** [comment]
~~The command appears to work, but the help says that the command does not exist~~ I tested this incorrectly, see below

2022-05-09-135034_2560x1440_scrot

**Comment by ghost** [comment]
I made 2 brand new accounts and logged in with level 1 characters, then ran the following on a separate GM account

```plaintext
.bindraf 3 4
.raf lookup
.raf lookup 3
.raf lookup 4
```

2022-05-09-141904_2560x1440_scrot

Appears that things are not working as intended

**Comment by 55Honey** [comment]
Thanks for the tests so far @fputs 🙏 
Should be fixed now!

**Comment by ghost** [comment]
`.raf lookup 3` is working as intended now. Looks good @55Honey

2022-05-10-101722_2560x1440_scrot

**Pull request merged**
